# Project meta configuration
PROJECT_NAME := cpp-direct-sprite-demo
MDKROOT := ../../mdk

# Project directories.
SRCDIR := src
RESDIR := res
OBJDIR := obj

# Sources.
SOURCES_CPP := $(shell find $(SRCDIR) -type f -name '*.cpp')

include $(MDKROOT)/md-rules.mk
