# Project meta configuration
PROJECT_NAME := cpp-direct-sprite-demo
MDKROOT := ../../mdk

# Project directories.
SRCDIR := src
RESDIR := res
OBJDIR := obj

# Sources.
SOURCES_CPP := $(shell find $(SRCDIR)/ -type f -name '*.cpp')
RESOURCES_LIST := $(shell find $(RESDIR)/ -type f -name '*')

include $(MDKROOT)/md-rules.mk

# Any additional build targets may go here.
# Please read about EXTERNAL_DEPS and EXTERNAL_ARTIFACTS in readme.md.
