# Project meta configuration
PROJECT_NAME := controller
MDKROOT := ../../mdk

# Project directories.
SRCDIR := src
RESDIR := res
OBJDIR := obj

# Sources.
SOURCES_C := $(shell find $(SRCDIR) -type f -name '*.c')

include $(MDKROOT)/md-rules.mk
