# Project meta configuration
PROJECT_NAME := mdsdrv-usage
MDKROOT := ../../mdk

# Project directories.
SRCDIR := src
RESDIR := res
OBJDIR := obj
PCMDIR := pcm

# Sources.
SOURCES_C := $(shell find $(SRCDIR) -type f -name '*.c')

# TARGET_SYSTEM := MDK_TARGET_C2
# MDK_C2_ADPCM := ../system-c2-demo/adpcm.bin

include $(MDKROOT)/md-rules.mk
